# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autobotUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 674)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fsvjoy_widget = CustomButton(self.centralwidget)
        self.fsvjoy_widget.setGeometry(QtCore.QRect(370, 350, 180, 180))
        self.fsvjoy_widget.setMinimumSize(QtCore.QSize(180, 180))
        self.fsvjoy_widget.setMaximumSize(QtCore.QSize(180, 180))
        self.fsvjoy_widget.setObjectName("fsvjoy_widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 111, 17))
        self.label.setObjectName("label")
        self.cmdveltopic = QtWidgets.QLineEdit(self.centralwidget)
        self.cmdveltopic.setGeometry(QtCore.QRect(140, 80, 113, 25))
        self.cmdveltopic.setObjectName("cmdveltopic")
        self.settopicButton = QtWidgets.QPushButton(self.centralwidget)
        self.settopicButton.setGeometry(QtCore.QRect(270, 80, 89, 25))
        self.settopicButton.setObjectName("settopicButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(260, 130, 241, 58))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.linear_number = QtWidgets.QLineEdit(self.widget)
        self.linear_number.setAlignment(QtCore.Qt.AlignCenter)
        self.linear_number.setObjectName("linear_number")
        self.gridLayout.addWidget(self.linear_number, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.angular_number = QtWidgets.QLineEdit(self.widget)
        self.angular_number.setAlignment(QtCore.Qt.AlignCenter)
        self.angular_number.setObjectName("angular_number")
        self.gridLayout.addWidget(self.angular_number, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionxianshi = QtWidgets.QAction(MainWindow)
        self.actionxianshi.setObjectName("actionxianshi")
        self.menu.addAction(self.actionxianshi)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "运动控制话题"))
        self.settopicButton.setText(_translate("MainWindow", "设置话题"))
        self.label_2.setText(_translate("MainWindow", "线速度"))
        self.label_3.setText(_translate("MainWindow", "角速度"))
        self.menu.setTitle(_translate("MainWindow", "基础信息"))
        self.actionxianshi.setText(_translate("MainWindow", "xianshi"))
from custombutton import CustomButton
