// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/transform/proto/timestamped_transform.proto

#include "cartographer/transform/proto/timestamped_transform.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Rigid3d;
}  // namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto
namespace cartographer {
namespace transform {
namespace proto {
class TimestampedTransformDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TimestampedTransform>
      _instance;
} _TimestampedTransform_default_instance_;
}  // namespace proto
}  // namespace transform
}  // namespace cartographer
namespace protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto {
static void InitDefaultsTimestampedTransform() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cartographer::transform::proto::_TimestampedTransform_default_instance_;
    new (ptr) ::cartographer::transform::proto::TimestampedTransform();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cartographer::transform::proto::TimestampedTransform::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_TimestampedTransform =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsTimestampedTransform}, {
      &protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::scc_info_Rigid3d.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_TimestampedTransform.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::transform::proto::TimestampedTransform, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::transform::proto::TimestampedTransform, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::transform::proto::TimestampedTransform, transform_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cartographer::transform::proto::TimestampedTransform)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cartographer::transform::proto::_TimestampedTransform_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "cartographer/transform/proto/timestamped_transform.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n8cartographer/transform/proto/timestamp"
      "ed_transform.proto\022\034cartographer.transfo"
      "rm.proto\032,cartographer/transform/proto/t"
      "ransform.proto\"^\n\024TimestampedTransform\022\014"
      "\n\004time\030\001 \001(\003\0228\n\ttransform\030\002 \001(\0132%.cartog"
      "rapher.transform.proto.Rigid3db\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 238);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/transform/proto/timestamped_transform.proto", &protobuf_RegisterTypes);
  ::protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto
namespace cartographer {
namespace transform {
namespace proto {

// ===================================================================

void TimestampedTransform::InitAsDefaultInstance() {
  ::cartographer::transform::proto::_TimestampedTransform_default_instance_._instance.get_mutable()->transform_ = const_cast< ::cartographer::transform::proto::Rigid3d*>(
      ::cartographer::transform::proto::Rigid3d::internal_default_instance());
}
void TimestampedTransform::clear_transform() {
  if (GetArenaNoVirtual() == NULL && transform_ != NULL) {
    delete transform_;
  }
  transform_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TimestampedTransform::kTimeFieldNumber;
const int TimestampedTransform::kTransformFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TimestampedTransform::TimestampedTransform()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::scc_info_TimestampedTransform.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.transform.proto.TimestampedTransform)
}
TimestampedTransform::TimestampedTransform(const TimestampedTransform& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_transform()) {
    transform_ = new ::cartographer::transform::proto::Rigid3d(*from.transform_);
  } else {
    transform_ = NULL;
  }
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:cartographer.transform.proto.TimestampedTransform)
}

void TimestampedTransform::SharedCtor() {
  ::memset(&transform_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&time_) -
      reinterpret_cast<char*>(&transform_)) + sizeof(time_));
}

TimestampedTransform::~TimestampedTransform() {
  // @@protoc_insertion_point(destructor:cartographer.transform.proto.TimestampedTransform)
  SharedDtor();
}

void TimestampedTransform::SharedDtor() {
  if (this != internal_default_instance()) delete transform_;
}

void TimestampedTransform::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TimestampedTransform::descriptor() {
  ::protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TimestampedTransform& TimestampedTransform::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::scc_info_TimestampedTransform.base);
  return *internal_default_instance();
}


void TimestampedTransform::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.transform.proto.TimestampedTransform)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && transform_ != NULL) {
    delete transform_;
  }
  transform_ = NULL;
  time_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool TimestampedTransform::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.transform.proto.TimestampedTransform)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .cartographer.transform.proto.Rigid3d transform = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_transform()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.transform.proto.TimestampedTransform)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.transform.proto.TimestampedTransform)
  return false;
#undef DO_
}

void TimestampedTransform::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.transform.proto.TimestampedTransform)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 time = 1;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->time(), output);
  }

  // .cartographer.transform.proto.Rigid3d transform = 2;
  if (this->has_transform()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_transform(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.transform.proto.TimestampedTransform)
}

::google::protobuf::uint8* TimestampedTransform::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.transform.proto.TimestampedTransform)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 time = 1;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->time(), target);
  }

  // .cartographer.transform.proto.Rigid3d transform = 2;
  if (this->has_transform()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_transform(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.transform.proto.TimestampedTransform)
  return target;
}

size_t TimestampedTransform::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.transform.proto.TimestampedTransform)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .cartographer.transform.proto.Rigid3d transform = 2;
  if (this->has_transform()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *transform_);
  }

  // int64 time = 1;
  if (this->time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TimestampedTransform::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.transform.proto.TimestampedTransform)
  GOOGLE_DCHECK_NE(&from, this);
  const TimestampedTransform* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TimestampedTransform>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.transform.proto.TimestampedTransform)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.transform.proto.TimestampedTransform)
    MergeFrom(*source);
  }
}

void TimestampedTransform::MergeFrom(const TimestampedTransform& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.transform.proto.TimestampedTransform)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_transform()) {
    mutable_transform()->::cartographer::transform::proto::Rigid3d::MergeFrom(from.transform());
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
}

void TimestampedTransform::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.transform.proto.TimestampedTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TimestampedTransform::CopyFrom(const TimestampedTransform& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.transform.proto.TimestampedTransform)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimestampedTransform::IsInitialized() const {
  return true;
}

void TimestampedTransform::Swap(TimestampedTransform* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TimestampedTransform::InternalSwap(TimestampedTransform* other) {
  using std::swap;
  swap(transform_, other->transform_);
  swap(time_, other->time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TimestampedTransform::GetMetadata() const {
  protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cartographer_2ftransform_2fproto_2ftimestamped_5ftransform_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace transform
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::cartographer::transform::proto::TimestampedTransform* Arena::CreateMaybeMessage< ::cartographer::transform::proto::TimestampedTransform >(Arena* arena) {
  return Arena::CreateInternal< ::cartographer::transform::proto::TimestampedTransform >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
