// Generated by gencpp from file autobot_msgs/IMU.msg
// DO NOT EDIT!


#ifndef AUTOBOT_MSGS_MESSAGE_IMU_H
#define AUTOBOT_MSGS_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace autobot_msgs
{
template <class ContainerAllocator>
struct IMU_
{
  typedef IMU_<ContainerAllocator> Type;

  IMU_()
    : linear_acceleration()
    , angular_velocity()
    , angle()
    , temperature(0.0)  {
    }
  IMU_(const ContainerAllocator& _alloc)
    : linear_acceleration(_alloc)
    , angular_velocity(_alloc)
    , angle(_alloc)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angle_type;
  _angle_type angle;

   typedef double _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::autobot_msgs::IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autobot_msgs::IMU_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_

typedef ::autobot_msgs::IMU_<std::allocator<void> > IMU;

typedef boost::shared_ptr< ::autobot_msgs::IMU > IMUPtr;
typedef boost::shared_ptr< ::autobot_msgs::IMU const> IMUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autobot_msgs::IMU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autobot_msgs::IMU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autobot_msgs::IMU_<ContainerAllocator1> & lhs, const ::autobot_msgs::IMU_<ContainerAllocator2> & rhs)
{
  return lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.angle == rhs.angle &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autobot_msgs::IMU_<ContainerAllocator1> & lhs, const ::autobot_msgs::IMU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autobot_msgs::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autobot_msgs::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autobot_msgs::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autobot_msgs::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobot_msgs::IMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobot_msgs::IMU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autobot_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c042b8627ba8a889d53ed18c948dae0d";
  }

  static const char* value(const ::autobot_msgs::IMU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc042b8627ba8a889ULL;
  static const uint64_t static_value2 = 0xd53ed18c948dae0dULL;
};

template<class ContainerAllocator>
struct DataType< ::autobot_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autobot_msgs/IMU";
  }

  static const char* value(const ::autobot_msgs::IMU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autobot_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"geometry_msgs/Vector3 angular_velocity\n"
"geometry_msgs/Vector3 angle\n"
"\n"
"float64 temperature\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::autobot_msgs::IMU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autobot_msgs::IMU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_acceleration);
      stream.next(m.angular_velocity);
      stream.next(m.angle);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autobot_msgs::IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autobot_msgs::IMU_<ContainerAllocator>& v)
  {
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "angle: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angle);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOBOT_MSGS_MESSAGE_IMU_H
