set(_CATKIN_CURRENT_PACKAGE "rosserial_stm32")
set(rosserial_stm32_VERSION "0.0.0")
set(rosserial_stm32_MAINTAINER "Kenta Yonekura(a.k.a. yoneken) <yoneken@ieee.org>")
set(rosserial_stm32_PACKAGE_FORMAT "1")
set(rosserial_stm32_BUILD_DEPENDS "message_generation")
set(rosserial_stm32_BUILD_EXPORT_DEPENDS "message_runtime" "rospy" "rosserial_client" "rosserial_msgs")
set(rosserial_stm32_BUILDTOOL_DEPENDS "catkin")
set(rosserial_stm32_BUILDTOOL_EXPORT_DEPENDS )
set(rosserial_stm32_EXEC_DEPENDS "message_runtime" "rospy" "rosserial_client" "rosserial_msgs")
set(rosserial_stm32_RUN_DEPENDS "message_runtime" "rospy" "rosserial_client" "rosserial_msgs")
set(rosserial_stm32_TEST_DEPENDS )
set(rosserial_stm32_DOC_DEPENDS )
set(rosserial_stm32_URL_WEBSITE "")
set(rosserial_stm32_URL_BUGTRACKER "")
set(rosserial_stm32_URL_REPOSITORY "")
set(rosserial_stm32_DEPRECATED "")