set(_CATKIN_CURRENT_PACKAGE "autobot_msgs")
set(autobot_msgs_VERSION "0.0.0")
set(autobot_msgs_MAINTAINER "dream <dream@todo.todo>")
set(autobot_msgs_PACKAGE_FORMAT "2")
set(autobot_msgs_BUILD_DEPENDS "std_msgs" "geometry_msgs" "message_generation")
set(autobot_msgs_BUILD_EXPORT_DEPENDS "std_msgs" "geometry_msgs")
set(autobot_msgs_BUILDTOOL_DEPENDS "catkin")
set(autobot_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(autobot_msgs_EXEC_DEPENDS "std_msgs" "geometry_msgs" "message_runtime")
set(autobot_msgs_RUN_DEPENDS "std_msgs" "geometry_msgs" "message_runtime")
set(autobot_msgs_TEST_DEPENDS )
set(autobot_msgs_DOC_DEPENDS )
set(autobot_msgs_URL_WEBSITE "")
set(autobot_msgs_URL_BUGTRACKER "")
set(autobot_msgs_URL_REPOSITORY "")
set(autobot_msgs_DEPRECATED "")