set(_CATKIN_CURRENT_PACKAGE "autobot_simulation")
set(autobot_simulation_VERSION "0.0.0")
set(autobot_simulation_MAINTAINER "dream <dream@todo.todo>")
set(autobot_simulation_PACKAGE_FORMAT "2")
set(autobot_simulation_BUILD_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(autobot_simulation_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(autobot_simulation_BUILDTOOL_DEPENDS "catkin")
set(autobot_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(autobot_simulation_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(autobot_simulation_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "urdf" "xacro")
set(autobot_simulation_TEST_DEPENDS )
set(autobot_simulation_DOC_DEPENDS )
set(autobot_simulation_URL_WEBSITE "")
set(autobot_simulation_URL_BUGTRACKER "")
set(autobot_simulation_URL_REPOSITORY "")
set(autobot_simulation_DEPRECATED "")