set(_CATKIN_CURRENT_PACKAGE "autobot_rosserial")
set(autobot_rosserial_VERSION "0.0.0")
set(autobot_rosserial_MAINTAINER "dream <dream@todo.todo>")
set(autobot_rosserial_PACKAGE_FORMAT "2")
set(autobot_rosserial_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_rosserial_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_rosserial_BUILDTOOL_DEPENDS "catkin")
set(autobot_rosserial_BUILDTOOL_EXPORT_DEPENDS )
set(autobot_rosserial_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_rosserial_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_rosserial_TEST_DEPENDS )
set(autobot_rosserial_DOC_DEPENDS )
set(autobot_rosserial_URL_WEBSITE "")
set(autobot_rosserial_URL_BUGTRACKER "")
set(autobot_rosserial_URL_REPOSITORY "")
set(autobot_rosserial_DEPRECATED "")