set(_CATKIN_CURRENT_PACKAGE "autobot_gui")
set(autobot_gui_VERSION "0.0.0")
set(autobot_gui_MAINTAINER "dream <dream@todo.todo>")
set(autobot_gui_PACKAGE_FORMAT "2")
set(autobot_gui_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_gui_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_gui_BUILDTOOL_DEPENDS "catkin")
set(autobot_gui_BUILDTOOL_EXPORT_DEPENDS )
set(autobot_gui_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_gui_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(autobot_gui_TEST_DEPENDS )
set(autobot_gui_DOC_DEPENDS )
set(autobot_gui_URL_WEBSITE "")
set(autobot_gui_URL_BUGTRACKER "")
set(autobot_gui_URL_REPOSITORY "")
set(autobot_gui_DEPRECATED "")