set(_CATKIN_CURRENT_PACKAGE "lidar_slam")
set(lidar_slam_VERSION "0.0.0")
set(lidar_slam_MAINTAINER "dream <dream@todo.todo>")
set(lidar_slam_PACKAGE_FORMAT "2")
set(lidar_slam_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(lidar_slam_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(lidar_slam_BUILDTOOL_DEPENDS "catkin")
set(lidar_slam_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_slam_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(lidar_slam_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(lidar_slam_TEST_DEPENDS )
set(lidar_slam_DOC_DEPENDS )
set(lidar_slam_URL_WEBSITE "")
set(lidar_slam_URL_BUGTRACKER "")
set(lidar_slam_URL_REPOSITORY "")
set(lidar_slam_DEPRECATED "")