// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/normal_estimation_options_2d.proto

#include "cartographer/mapping/proto/normal_estimation_options_2d.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace proto {
class NormalEstimationOptions2DDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NormalEstimationOptions2D>
      _instance;
} _NormalEstimationOptions2D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto {
static void InitDefaultsNormalEstimationOptions2D() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cartographer::mapping::proto::_NormalEstimationOptions2D_default_instance_;
    new (ptr) ::cartographer::mapping::proto::NormalEstimationOptions2D();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::cartographer::mapping::proto::NormalEstimationOptions2D::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NormalEstimationOptions2D =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNormalEstimationOptions2D}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NormalEstimationOptions2D.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::mapping::proto::NormalEstimationOptions2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::mapping::proto::NormalEstimationOptions2D, num_normal_samples_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::cartographer::mapping::proto::NormalEstimationOptions2D, sample_radius_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cartographer::mapping::proto::NormalEstimationOptions2D)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::cartographer::mapping::proto::_NormalEstimationOptions2D_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "cartographer/mapping/proto/normal_estimation_options_2d.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n=cartographer/mapping/proto/normal_esti"
      "mation_options_2d.proto\022\032cartographer.ma"
      "pping.proto\"N\n\031NormalEstimationOptions2D"
      "\022\032\n\022num_normal_samples\030\001 \001(\005\022\025\n\rsample_r"
      "adius\030\002 \001(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 179);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping/proto/normal_estimation_options_2d.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

void NormalEstimationOptions2D::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NormalEstimationOptions2D::kNumNormalSamplesFieldNumber;
const int NormalEstimationOptions2D::kSampleRadiusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NormalEstimationOptions2D::NormalEstimationOptions2D()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::scc_info_NormalEstimationOptions2D.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.proto.NormalEstimationOptions2D)
}
NormalEstimationOptions2D::NormalEstimationOptions2D(const NormalEstimationOptions2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&num_normal_samples_, &from.num_normal_samples_,
    static_cast<size_t>(reinterpret_cast<char*>(&sample_radius_) -
    reinterpret_cast<char*>(&num_normal_samples_)) + sizeof(sample_radius_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.proto.NormalEstimationOptions2D)
}

void NormalEstimationOptions2D::SharedCtor() {
  ::memset(&num_normal_samples_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sample_radius_) -
      reinterpret_cast<char*>(&num_normal_samples_)) + sizeof(sample_radius_));
}

NormalEstimationOptions2D::~NormalEstimationOptions2D() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.proto.NormalEstimationOptions2D)
  SharedDtor();
}

void NormalEstimationOptions2D::SharedDtor() {
}

void NormalEstimationOptions2D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NormalEstimationOptions2D::descriptor() {
  ::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NormalEstimationOptions2D& NormalEstimationOptions2D::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::scc_info_NormalEstimationOptions2D.base);
  return *internal_default_instance();
}


void NormalEstimationOptions2D::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&num_normal_samples_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&sample_radius_) -
      reinterpret_cast<char*>(&num_normal_samples_)) + sizeof(sample_radius_));
  _internal_metadata_.Clear();
}

bool NormalEstimationOptions2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 num_normal_samples = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_normal_samples_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float sample_radius = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &sample_radius_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.proto.NormalEstimationOptions2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.proto.NormalEstimationOptions2D)
  return false;
#undef DO_
}

void NormalEstimationOptions2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_normal_samples = 1;
  if (this->num_normal_samples() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->num_normal_samples(), output);
  }

  // float sample_radius = 2;
  if (this->sample_radius() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->sample_radius(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.proto.NormalEstimationOptions2D)
}

::google::protobuf::uint8* NormalEstimationOptions2D::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 num_normal_samples = 1;
  if (this->num_normal_samples() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->num_normal_samples(), target);
  }

  // float sample_radius = 2;
  if (this->sample_radius() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->sample_radius(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.proto.NormalEstimationOptions2D)
  return target;
}

size_t NormalEstimationOptions2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 num_normal_samples = 1;
  if (this->num_normal_samples() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_normal_samples());
  }

  // float sample_radius = 2;
  if (this->sample_radius() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NormalEstimationOptions2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  const NormalEstimationOptions2D* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NormalEstimationOptions2D>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.proto.NormalEstimationOptions2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.proto.NormalEstimationOptions2D)
    MergeFrom(*source);
  }
}

void NormalEstimationOptions2D::MergeFrom(const NormalEstimationOptions2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.num_normal_samples() != 0) {
    set_num_normal_samples(from.num_normal_samples());
  }
  if (from.sample_radius() != 0) {
    set_sample_radius(from.sample_radius());
  }
}

void NormalEstimationOptions2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NormalEstimationOptions2D::CopyFrom(const NormalEstimationOptions2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.proto.NormalEstimationOptions2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NormalEstimationOptions2D::IsInitialized() const {
  return true;
}

void NormalEstimationOptions2D::Swap(NormalEstimationOptions2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NormalEstimationOptions2D::InternalSwap(NormalEstimationOptions2D* other) {
  using std::swap;
  swap(num_normal_samples_, other->num_normal_samples_);
  swap(sample_radius_, other->sample_radius_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NormalEstimationOptions2D::GetMetadata() const {
  protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::cartographer::mapping::proto::NormalEstimationOptions2D* Arena::CreateMaybeMessage< ::cartographer::mapping::proto::NormalEstimationOptions2D >(Arena* arena) {
  return Arena::CreateInternal< ::cartographer::mapping::proto::NormalEstimationOptions2D >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
