// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/normal_estimation_options_2d.proto

#ifndef PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto
#define PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto 

namespace protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto
namespace cartographer {
namespace mapping {
namespace proto {
class NormalEstimationOptions2D;
class NormalEstimationOptions2DDefaultTypeInternal;
extern NormalEstimationOptions2DDefaultTypeInternal _NormalEstimationOptions2D_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
namespace google {
namespace protobuf {
template<> ::cartographer::mapping::proto::NormalEstimationOptions2D* Arena::CreateMaybeMessage<::cartographer::mapping::proto::NormalEstimationOptions2D>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class NormalEstimationOptions2D : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.NormalEstimationOptions2D) */ {
 public:
  NormalEstimationOptions2D();
  virtual ~NormalEstimationOptions2D();

  NormalEstimationOptions2D(const NormalEstimationOptions2D& from);

  inline NormalEstimationOptions2D& operator=(const NormalEstimationOptions2D& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NormalEstimationOptions2D(NormalEstimationOptions2D&& from) noexcept
    : NormalEstimationOptions2D() {
    *this = ::std::move(from);
  }

  inline NormalEstimationOptions2D& operator=(NormalEstimationOptions2D&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NormalEstimationOptions2D& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NormalEstimationOptions2D* internal_default_instance() {
    return reinterpret_cast<const NormalEstimationOptions2D*>(
               &_NormalEstimationOptions2D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NormalEstimationOptions2D* other);
  friend void swap(NormalEstimationOptions2D& a, NormalEstimationOptions2D& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NormalEstimationOptions2D* New() const final {
    return CreateMaybeMessage<NormalEstimationOptions2D>(NULL);
  }

  NormalEstimationOptions2D* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NormalEstimationOptions2D>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NormalEstimationOptions2D& from);
  void MergeFrom(const NormalEstimationOptions2D& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NormalEstimationOptions2D* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 num_normal_samples = 1;
  void clear_num_normal_samples();
  static const int kNumNormalSamplesFieldNumber = 1;
  ::google::protobuf::int32 num_normal_samples() const;
  void set_num_normal_samples(::google::protobuf::int32 value);

  // float sample_radius = 2;
  void clear_sample_radius();
  static const int kSampleRadiusFieldNumber = 2;
  float sample_radius() const;
  void set_sample_radius(float value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.NormalEstimationOptions2D)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 num_normal_samples_;
  float sample_radius_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NormalEstimationOptions2D

// int32 num_normal_samples = 1;
inline void NormalEstimationOptions2D::clear_num_normal_samples() {
  num_normal_samples_ = 0;
}
inline ::google::protobuf::int32 NormalEstimationOptions2D::num_normal_samples() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.NormalEstimationOptions2D.num_normal_samples)
  return num_normal_samples_;
}
inline void NormalEstimationOptions2D::set_num_normal_samples(::google::protobuf::int32 value) {
  
  num_normal_samples_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.NormalEstimationOptions2D.num_normal_samples)
}

// float sample_radius = 2;
inline void NormalEstimationOptions2D::clear_sample_radius() {
  sample_radius_ = 0;
}
inline float NormalEstimationOptions2D::sample_radius() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.NormalEstimationOptions2D.sample_radius)
  return sample_radius_;
}
inline void NormalEstimationOptions2D::set_sample_radius(float value) {
  
  sample_radius_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.NormalEstimationOptions2D.sample_radius)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fnormal_5festimation_5foptions_5f2d_2eproto
