set(_CATKIN_CURRENT_PACKAGE "realsense_model")
set(realsense_model_VERSION "1.0.0")
set(realsense_model_MAINTAINER " <TODO@email.com>")
set(realsense_model_PACKAGE_FORMAT "2")
set(realsense_model_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(realsense_model_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(realsense_model_BUILDTOOL_DEPENDS "catkin")
set(realsense_model_BUILDTOOL_EXPORT_DEPENDS )
set(realsense_model_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(realsense_model_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(realsense_model_TEST_DEPENDS )
set(realsense_model_DOC_DEPENDS )
set(realsense_model_URL_WEBSITE "")
set(realsense_model_URL_BUGTRACKER "")
set(realsense_model_URL_REPOSITORY "")
set(realsense_model_DEPRECATED "")